### PR TITLE
Autoscroll to bottom broken #276

### LINKED ISSUE #276: Autoscroll to bottom broken
Doesn't seem to work now. Probably something regressed during the update to the model manager.

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #276

### CODE REVIEW

File: src/main/java/address/browser/BrowserManager.java [hunk 1]
```diff
@@ -101,7 +100,8 @@ public synchronized void loadProfilePage(ReadOnlyViewablePerson person) {
         try {
             Page page = hyperBrowser.get().loadUrls(person.profilePageUrl(), listOfFutureUrl);
             GithubProfilePage gPage = new GithubProfilePage(page);
-            gPage.setPageLoadFinishListener(b -> Platform.runLater(() -> gPage.activateAutomateClickingAndScrolling()));
+            gPage.executePageLoadedTasks();
```
Comment (HansNewbie) [inline src/main/java/address/browser/BrowserManager.java]: We need this to fix the bug?

Comment (yl-coder) [inline src/main/java/address/browser/BrowserManager.java]: Yes, if the page is already loaded, then execute the tasks.

Comment (HansNewbie) [inline src/main/java/address/browser/BrowserManager.java]: If the call below (`setPageLoadFinishListener`) is not enough, then sure. No more comments.
