### PR TITLE
Repeated app resizing fails #456

### LINKED ISSUE #456: Repeated app resizing fails
At least on Mac, it will correctly maximize and reset to default size the first 2 times the key combination is pressed. 
However, from then on it will remain at the same default size (with some vertical movement every 2 times the keys are pressed).

Possible solution: http://stackoverflow.com/questions/18998671/set-height-and-width-of-stage-and-scene-in-javafx
```
protected void setDefaultSize() {
        primaryStage.setMaximized(false);
        primaryStage.setIconified(false);
        primaryStage.hide();
        primaryStage.show();
}
```
works, but causes flinching of the app.

### PR DESCRIPTION
**Pull request by m133225**
Fixes #456

Code does not seem to make sense, but works on Mac. Will further test on Windows machine at home.

### CODE REVIEW

File: src/main/java/address/controller/MainController.java [hunk 1]
```diff
@@ -575,9 +560,15 @@ private void minimizeWindow() {
         primaryStage.setMaximized(false);
     }
 
-    private void maximizeWindow() {
+    private void resizeWindow() {
+        logger.info("Resizing window");
+        if (OsDetector.isOnMac()) primaryStage.hide();
         primaryStage.setMaximized(true);
         primaryStage.setIconified(false);
+        if (OsDetector.isOnMac()) primaryStage.show();
```
Comment (damithc) [inline src/main/java/address/controller/MainController.java]: May want to comment on why the code is like that.

File: src/main/java/address/controller/MainController.java [hunk 2]
```diff
@@ -575,9 +560,29 @@ private void minimizeWindow() {
...
+                // on Mac, setMaximized seems to work like "setResize"
+                // isMaximized also does not seem to return the correct value
+                primaryStage.setMaximized(true);
+            } else {
+                primaryStage.setMaximized(!primaryStage.isMaximized());
+            }
+        }
+
+        logger.debug("Stage width: {}", primaryStage.getWidth());
+        logger.debug("Stage height: {}", primaryStage.getHeight());
```
Comment (damithc) [inline src/main/java/address/controller/MainController.java]: I don't like the 'pregnant woman' shape (caused by short branch followed by deep branch) of the code, but not sure if it can be avoided.
```
\
/
\
 \
  \
   \
   /
  /
 /
/
```
