### PR TITLE
A test in KeyBindingsManagerApiTest fails locally #293

### LINKED ISSUE #293: A test in KeyBindingsManagerApiTest fails locally
The test `keyEventDetected_definedBinding_matchingEventRaised` fails locally on Mac.

### PR DESCRIPTION
**Pull request by damithc**
Fixes #293

### CODE REVIEW

**Comment by damithc** [comment]
@m133225 @HansNewbie see if this fix works in your Macs

**Comment by m133225** [comment]
Seems to be working.

File: src/test/java/address/util/PlatformSpecific.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
+package address.util;
+
+import java.io.BufferedReader;
+import java.io.IOException;
+import java.io.InputStreamReader;
+
+
+public final class PlatformSpecific {
```
Comment (HansNewbie) [inline src/test/java/address/util/PlatformSpecific.java]: I actually already created a class similar to this, named `OsDetector` in `util` of production since we have platform specific codes.

**Comment by HansNewbie** [comment]
The `KeyBindingsManagerApiTest` no longer fails.

**Comment by damithc** [comment]
OK, now that I know the fix works, I'll try to apply the technique in a tidier way.

**Comment by damithc** [comment]
Waiting for #289 to finish first (and reuse the solution)

**Comment by damithc** [comment]
@m133225 merge the keycombination fix as a separate PR so that this PR can use it?

**Comment by m133225** [comment]
Done in #332.

**Comment by damithc** [comment]
@m133225 @HansNewbie see if this passes on Mac.
I tried to reuse @m133225 's previous solution, but it didn't work for keybinding tests. Had to combine the two solutions in the end.

**Comment by m133225** [comment]
The `KeyBindingManagerApiTest` itself works both in headless and headful, but I think there is still a problem with the shortcut when calling `push` in GUI tests.
- Seems like META + KeyCode responds correctly in headful, and COMMAND + KeyCode responds correctly in headless
  - With this PR's solution (which converts `SHORTCUT` to `META`),
    - Headless mode
      -`push(COMMAND, A)` passes
      -`push(KeyCodeCombination(A, SHORTCUT/META))` fails
    - Headful mode
      -`push(COMMAND, A)` fails
      - `push(KeyCodeCombination(A, SHORTCUT/META))` passes

**Comment by damithc** [comment]
Should we use `COMMAND` instead? If that doesn't work, we'll have to select based on the test mode :-p

**Comment by m133225** [comment]
Do you mean converting `SHORTCUT` to `COMMAND` (like the current master)? That still shouldn't work in headful mode.

**Comment by HansNewbie** [comment]
Works on Mac for the `KeyBindingManagerApiTest`.

**Comment by damithc** [comment]
In that case we'll probably need to vary the keys based on the test mode too. May be introduce a `TestEnv` class (similar to `OsDetector` and use it in the relevant methods? @m133225 can you continue this PR?

**Comment by m133225** [comment]
Will we still manually fire events in `KeyBindingManagerApiTest` if it is fixed? If we are, we could merge this first (without the `push` changes) and work on the headful/headless issue in another PR.

**Comment by m133225** [comment]
@damithc Updated it. Works locally on Mac in both headless and headful modes. Works on Travis in headless mode too. Could you try `TagEditDialogTest` (as well as `KeyBindingsManagerApiTest`) on Windows?

**Comment by damithc** [comment]
Headless: passed in one try, both times I tried.
Headfull: tried three times. First two times some tests failed, but the failing tests passed when retried. Third time all tests passed in one try.
So I guess can merge.
