### PR TITLE
Change all FXML load errors dialog into assertion #288

### LINKED ISSUE #288: Change all FXML load errors dialog into assertion
As the FXMLs are suppose to be there and load without errors.

For example in this code segment
```
  public void showTagList(ObservableList<Tag> tags) {
        logger.debug("Loading tag list.");
        final String fxmlResourcePath = FXML_TAG_LIST;
        try {
            // Load the fxml file and create a new stage for the popup dialog.
            FXMLLoader loader = loadFxml(fxmlResourcePath);
            AnchorPane page = loader.load();

            Scene scene = new Scene(page);
            Stage dialogStage = loadDialogStage("List of Tags", primaryStage, scene);

            // Set the tag into the controller.
            TagListController tagListController = loader.getController();
            tagListController.setMainController(this);
            tagListController.setModelManager(modelManager);
            tagListController.setTags(tags);
            tagListController.setStage(dialogStage);

            // Show the dialog and wait until the user closes it
            dialogStage.showAndWait();
        } catch (IOException e) {
            logger.warn("Error loading tag list view: {}", e);
            showAlertDialogAndWait(AlertType.ERROR, "FXML Load Error", "Cannot load fxml for tag list.",
                                   "IOException when trying to load " + fxmlResourcePath);
        }
    }
```

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #288

### CODE REVIEW

**Comment by YijinL** [comment]
Repeating almost the same code for every fxml view, maybe can abstract it out as a method (that takes in view name as a string for error message customisation).
Then call that method in all the `catch (IOException)` blocks. So all the `assert` and `showAlertDialogAndWait` are centralised.

File: src/main/java/address/controller/MainController.java [hunk 1]
```diff
@@ -559,4 +545,10 @@ public void stop() {
         getPrimaryStage().hide();
         releaseResourcesForAppTermination();
     }
+
+    private void showAlertDialogWithAssertion(String title, String headerText, String contentText, String errorLocation) {
```
Comment (YijinL) [inline src/main/java/address/controller/MainController.java]: Name is too general, this is specifically for fxml load failures right?
How about something like `handleFatalFxmlLoadError`?

**Comment by YijinL** [comment]
no more comments
