### PR TITLE
Inject pref values in the TestApp for testing #475

### LINKED ISSUE #444: TestApp causes BufferOverflowException in headless mode
Probably the cloud console exceeding the frame buffer. This does not cause the tests to fail.
```
java.nio.BufferOverflowException
    	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
    	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:153)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    	at java.lang.Thread.run(Thread.java:745)
```

### LINKED ISSUE #475: Inject pref values in the TestApp for testing
Note: The pref values should be non-persistent, In case one test method modified the pref values. Every test methods should be initialized to that pref values.

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #475 
Fixes #444

### CODE REVIEW

**Comment by damithc** [comment]
As discussed, limit the change to TestApp file.

**Comment by damithc** [comment]
No comments from me.

File: src/test/java/address/TestApp.java [hunk 1]
```diff
@@ -56,6 +60,7 @@ protected Config initConfig(String configFilePath) {
     @Override
     protected UserPrefs initPrefs(Config config) {
         UserPrefs userPrefs = super.initPrefs(config);
+        userPrefs.setGuiSettings(new GuiSettings(600.0, 600.0, 0, 0));
```
Comment (m133225) [inline src/test/java/address/TestApp.java]: I think this may not be a good solution. Positioning the window at 0, 0 will also cause the headful tests to fail on Mac, since the top task-bar (whatever that's called) will cover the app UI elements.

Comment (yl-coder) [inline src/test/java/address/TestApp.java]: Right, perhaps i need to find a way to find best position based on OS.
