### PR TITLE
IOOBE while adding person #324

### LINKED ISSUE #324: IOOBE while adding person
This happened while I was trying to add and undo the add operation. Cannot reproduce though.
```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at address.util.collections.ReorderedList.getSourceIndex(ReorderedList.java:49)
	at address.util.collections.ReorderedList.get(ReorderedList.java:54)
	at javafx.scene.control.ListView$ListViewBitSetSelectionModel.getModelItem(ListView.java:1429)
	at javafx.scene.control.MultipleSelectionModelBase.lambda$new$34(MultipleSelectionModelBase.java:67)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyIntegerWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:176)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:142)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
	at javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:68)
	at javafx.scene.control.MultipleSelectionModelBase.shiftSelection(MultipleSelectionModelBase.java:294)
	at javafx.scene.control.ListView$ListViewBitSetSelectionModel.updateSelection(ListView.java:1377)
	at javafx.scene.control.ListView$ListViewBitSetSelectionModel.access$1500(ListView.java:1167)
	at javafx.scene.control.ListView$ListViewBitSetSelectionModel$2.onChanged(ListView.java:1248)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at address.util.collections.ReorderedList.sourceChanged(ReorderedList.java:44)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at address.util.FilteredList.sourceChanged(FilteredList.java:126)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:183)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:171)
	at address.model.datatypes.person.ReadOnlyPerson.removeOneById(ReadOnlyPerson.java:37)
	at address.model.datatypes.ViewableAddressBook.removePerson(ViewableAddressBook.java:87)
	at address.model.AddPersonCommand.lambda$finishWithCancel$70(AddPersonCommand.java:135)
	at address.util.PlatformExecUtil.lambda$runLaterAndWait$74(PlatformExecUtil.java:77)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #324

### CODE REVIEW

**Comment by yl-coder** [comment]
@YijinL can help to review this? thanks

**Comment by yl-coder** [comment]
Potentially fixes #326 also. I notice that get selectedItems from SelectionModel will have item that is not  ReadOnlyPerson. Therefore causing the NPE.

File: src/main/java/address/controller/PersonOverviewController.java [hunk 1]
```diff
@@ -117,7 +119,10 @@ private void initialize() {
      */
     @FXML
     private void handleDeletePersons() {
-        final List<ReadOnlyViewablePerson> selected = personListView.getSelectionModel().getSelectedItems();
+        final List<ReadOnlyViewablePerson> selected = new ArrayList<>(personListView.getSelectionModel()
+                                                                                    .getSelectedItems());
+        selected.removeIf(p -> !(p instanceof  ReadOnlyViewablePerson));
```
Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]: is this necessary

File: src/main/java/address/controller/PersonOverviewController.java [hunk 2]
```diff
@@ -172,14 +178,14 @@ private void handleEditPerson() {
...
-        selectedIndexes.stream().forEach(selectedIndex -> {
-            if (selectedIndex >= 0) {
-                final ReadOnlyPerson cancelTarget = personListView.getItems().get(selectedIndex);
-                modelManager.cancelPersonChangeCommand(cancelTarget);
-            } else {
-                showNoSelectionAlert(); // Nothing selected.
-            }
+        final List<ReadOnlyViewablePerson> selectedPersons = new ArrayList<>(personListView.getSelectionModel().getSelectedItems());
+        selectedPersons.removeIf(p -> !(p instanceof ReadOnlyViewablePerson));
+        if (selectedPersons.size() == 0) {
```
Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]: selectedPersons.isEmpty() would be cleaner

File: src/main/java/address/controller/PersonOverviewController.java (hunk 1 above)
Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: As mentioned,  I notice that get selectedItems from SelectionModel will have item that is not ReadOnlyPerson. Therefore causing the NPE at #326.

File: src/main/java/address/controller/PersonOverviewController.java (hunk 2 above)
Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: ok

File: src/main/java/address/controller/PersonOverviewController.java (hunk 1 above)
Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: You can try this on master :

1) create a new person
2) select the person and uno
3) now nothing is selected. Press D
4) null is deleted (because selectionItems has a null item)
image

Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]: Perhaps remove this line and change the below if-check:
`if (selected.isEmpty() || selected.contains(null))`

Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: it doesn't work
image

Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: i think you can't use contain() for null.

Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: stream can't work with null. using normal for loop

Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]: But the javadocs says contains works for null, i will try on my end too

Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]: You're right, it means the returned list from `getSelectionModel.getSelectedItems` does not follow the javadoc `Collection.contains` interface.... zzzz..

Try `if (selected.isEmpty() || selected.stream().filter(Objects::isNull).findAny().isPresent())`

File: src/main/java/address/controller/PersonOverviewController.java [hunk 3]
```diff
@@ -129,6 +129,15 @@ private void handleDeletePersons() {
...
     }
 
+    private boolean isListContainingNullObject(List<ReadOnlyViewablePerson> selected) {
+        for (Object obj : selected) {
+            if (obj == null){
+                return true;
+            }
+        }
+        return false;
+    }
```
Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]:
```java
public static boolean collectionContainsNull(Collection<?> col) {
    return col.stream().anyMatch(Objects::isNull);
}
```
Not sure why argument parameter has to be ReadOnlyViewablePerson, and can use stream to make things neater

File: src/main/java/address/controller/PersonOverviewController.java [hunk 4]
```diff
@@ -144,6 +153,12 @@ private void handleNewPerson() {
      */
     private void handleRetagPersons() {
         List<ReadOnlyViewablePerson> selectedPersons = personListView.getSelectionModel().getSelectedItems();
+
+        if (selectedPersons.isEmpty() || isListContainingNullObject(selectedPersons)) {
```
Comment (YijinL) [inline src/main/java/address/controller/PersonOverviewController.java]: This gets repeated many times, i suggest refactoring it out as a separate method, then can remove the isListContainingNullObject method too, something maybe like:
```java
public static boolean isSelectionValid() {
    return personListView.getSelectionModel().getSelectedItems().stream().anyMatch(Objects::isNull);
}
```

Comment (yl-coder) [inline src/main/java/address/controller/PersonOverviewController.java]: right. changed

**Comment by yl-coder** [comment]
@YijinL Anymore comments before merging this PR?

**Comment by YijinL** [comment]
No looks good
